# CoreDNS alerts based on https://github.com/povilasv/coredns-mixin
#
groups:
- name: coredns
  rules:
  - alert: CoreDNSDown
    annotations:
      message: 'CoreDNS has disappeared from Prometheus target discovery.'
    expr: 'sum by (cluster) (prometheus_heartbeat) unless (sum by (cluster) (up{job="coredns"} == 1))'
    for: 15m
    labels:
      scope: cluster
      severity: P1-Critical

  - alert: CoreDNSLatencyHigh
    annotations:
      message: 'CoreDNS has 99th percentile latency of {{ $value }} seconds for server {{ $labels.server }} zone {{ $labels.zone }}.'
    expr: 'histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job="coredns"}[5m])) by(server, zone, le, cluster)) > 4'
    for: 10m
    labels:
      scope: cluster
      severity: P2-Major

  - alert: CoreDNSErrorsHigh
    annotations:
      message: 'CoreDNS is returning SERVFAIL for {{ $value | humanizePercentage }} of requests.'
    expr: '( sum by (cluster) ((rate(coredns_dns_responses_total{job="coredns",rcode="SERVFAIL"}[5m])) ) )/ ( sum by (cluster) (rate(coredns_dns_responses_total{job="coredns"}[5m])) ) > 0.03'
    for: 10m
    labels:
      scope: cluster
      severity: P2-Major

  - alert: CoreDNSErrorsHigh
    annotations:
      message: 'CoreDNS is returning SERVFAIL for {{ $value | humanizePercentage }} of requests.'
    expr: '( sum by (cluster) ((rate(coredns_dns_responses_total{job="coredns",rcode="SERVFAIL"}[5m])) ) )/ ( sum by (cluster) (rate(coredns_dns_responses_total{job="coredns"}[5m])) ) > 0.01'
    for: 10m
    labels:
      scope: cluster
      severity: P3-Minor

- name: coredns_forward
  rules:
  - alert: CoreDNSForwardLatencyHigh
    annotations:
      message: 'CoreDNS has 99th percentile latency of {{ $value }} seconds forwarding requests to {{ $labels.to }}.'
    expr: 'histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{job="coredns"}[5m])) by(to, le, cluster)) > 4'
    for: 10m
    labels:
      scope: cluster
      severity: P2-Major

  - alert: CoreDNSForwardErrorsHigh
    annotations:
      message: 'CoreDNS is returning SERVFAIL for {{ $value | humanizePercentage }} of forward requests to {{ $labels.to }}.'
    expr: 'sum(rate(coredns_forward_responses_total{job="coredns",rcode="SERVFAIL"}[5m])) by (to, cluster)/sum(rate(coredns_forward_responses_total{job="coredns"}[5m])) by (to, cluster) > 0.03'
    for: 10m
    labels:
      scope: cluster
      severity: P2-Major

  - alert: CoreDNSForwardErrorsHigh
    annotations:
      message: 'CoreDNS is returning SERVFAIL for {{ $value | humanizePercentage }} of forward requests to {{ $labels.to }}.'
    expr: 'sum(rate(coredns_forward_responses_total{job="coredns",rcode="SERVFAIL"}[5m])) by (to, cluster)/sum(rate(coredns_forward_responses_total{job="coredns"}[5m])) by (to, cluster) > 0.01'
    for: 10m
    labels:
      scope: cluster
      severity: P3-Minor

  - alert: CoreDNSForwardHealthcheckFailureCount
    annotations:
      message: 'CoreDNS health checks have failed to upstream server {{ $labels.to }}.'
    expr: 'sum(rate(coredns_forward_healthcheck_failures_total{job="coredns"}[5m])) by (to, cluster) > 0'
    for: 10m
    labels:
      scope: cluster
      severity: P3-Minor

  - alert: CoreDNSForwardHealthcheckBrokenCount
    annotations:
      message: 'CoreDNS health checks have failed for all upstream servers.'
    expr: 'sum(rate(coredns_forward_healthcheck_broken_total{job="coredns"}[5m])) by (cluster) > 0'
    for: 10m
    labels:
      scope: cluster
      severity: P3-Minor
