groups:
  - name: jobs.rules
    rules:
      - alert: JobFailed
        annotations:
          message: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete. Removing the failed job after investigation should clear this alert.'
          runbook: "${runbook_base_url}/namespace-alert-runbooks/job-failed/"
        expr: 'sum by (cluster, namespace, job_name) (kube_job_status_failed > 0)'
        for: 15m
        labels:
          scope: namespace
          severity: P3-Minor

      - alert: JobIncomplete
        annotations:
          message: 'Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than 12 hours to complete.'
          runbook: "${runbook_base_url}/namespace-alert-runbooks/job-incomplete/"
        expr: '(sum by (cluster, namespace, job_name) (kube_job_spec_completions) unless sum by (cluster, namespace, job_name) (kube_job_complete == 1)) unless sum by (cluster, namespace, job_name) (kube_job_status_failed == 1)'
        for: 12h
        labels:
          scope: namespace
          severity: P3-Minor

      - alert: CompletedJobsNotCleared
        annotations:
          message: 'Namespace {{ $labels.namespace }} has {{ $value }} completed jobs older than 24h.'
          runbook: "${runbook_base_url}/namespace-alert-runbooks/completed-jobs-not-cleared/"
        expr: 'count by (namespace, cluster) (kube_job_status_completion_time < (time() - 86400)) > 20'
        for: 15m
        labels:
          scope: namespace
          severity: P3-Minor
